#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LocSDKBindingDemo.Resource", IsApplication=true)]

namespace LocSDKBindingDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int TextView01 = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int addfence = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int frequence = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int geofencelog = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int geolocation = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int modeinfor = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int radio_bd09 = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int radio_bd09ll = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int radio_device = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int radio_gcj02 = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int radio_hight = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int radio_low = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int selectCoordinates = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int selectMode = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textView2 = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int textView3 = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int device_sensor_desc = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int error_code_desc = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int error_code_detail = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int hight_accuracy_desc = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int qa_callback = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int qa_callback_mail = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int qa_title = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int saving_battery_desc = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int startlocation = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int stoplocation = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
